### ISSUE TITLE
Ignores hidden fields and field access permissions

### ISSUE THREAD

**Issue by albanycomputers** [backdrop-contrib/token_embed_views#6]
When embedding a view... Hidden fields and fields where the viewer does not have access permissions are being shown.

![image](https://user-images.githubusercontent.com/1705388/198069244-043347ba-dc09-4a26-80cf-60d2bcd252e3.png)

This is the same view that is not being embedded

![image](https://user-images.githubusercontent.com/1705388/198072027-f6f741a4-9f9f-43df-91a9-8e1e755bb365.png)

**Comment by argiepiano** [comment]
@albanycomputers, this is strange about hidden fields. The module simply embeds the view using views_embed_view(), which should respect hidden fields. Is it possible for you to share a sample view to test?

As for respecting permissions, do you mean permission to access the view itself? Or are you talking about field permissions (through a contrib module)? If contrib, which one?

**Comment by argiepiano** [comment]
Yup, I can confirm that the edit link is shown when you embed the view. This is a limitation of the core function views_embed_view rather than Token Embed Views. I'd have to see if there is a workaround for this. BTW the Drupal 7 version has AFAIK the same issue

**Comment by argiepiano** [comment]
This is what's happening. Backdrop caches node pages, so the very first view of the node page after clearing caches gets cached, and that's the page that is served (directly from the cache). This is a known issue with other tokens that need to be fulfilled dynamically.

You can download the Entity Cache Administration module, and disable caching for a specific node type.
